-- CreateTable
CREATE TABLE "ScoreRow" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL,
    "value" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,
    CONSTRAINT "ScoreRow_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
