-- CreateTable
CREATE TABLE "Row" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Column" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "rowId" INTEGER NOT NULL,
    "statistic" INTEGER NOT NULL,
    CONSTRAINT "Column_rowId_fkey" FOREIGN KEY ("rowId") REFERENCES "Row" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
